### ISSUE TITLE
[Bug] In Nav Bar

### ISSUE THREAD

**Issue by cnu1812** [kubesimplify/website#123] opened 2022-07-18 13:15 UTC
### Description

The contact and newsletter button is not working on the nav bar.

### Screenshots

![Screenshot 2022-07-18 184326](https://user-images.githubusercontent.com/75531528/179519265-6f8c8bab-8b4d-4fdc-b04d-5924a142e090.png)

**Comment by chirag0002** [comment] 2022-07-22 18:09
I want to work on this issue, would you assign me?

cc: @AvineshTripathi @bhavyastar

**Comment by AvineshTripathi** [comment] 2022-07-27 07:05
Hey @chirag0002 sorry to keep you waiting, the problem is that we are not keeping the contact button and it should be removed. Instead you can start working on `navbar` responsiveness if that interest you

**Comment by chirag0002** [comment] 2022-07-28 13:07
Yeah @AvineshTripathi, it suits me fine. So, do I have to create another issue for the navbar's responsiveness or to continue on this issue with responsiveness?

**Comment by bhavyastar** [comment] 2022-07-28 13:20
You can continue your work on this issue itself.

**Comment by chirag0002** [comment] 2022-07-28 13:22
Ohk @bhavyastar, please do assign me this issue.

**Comment by bhavyastar** [comment] 2022-07-28 17:15
Assigned, You can start working on this. @chirag0002

**Comment by AvineshTripathi** [comment] 2022-08-07 06:28
@chirag0002 any updates?

**Comment by chirag0002** [comment] 2022-08-07 10:25
@AvineshTripathi I think Bishal has done the responsiveness and committed it 6 days ago along with some other issues.
In short responsiveness of the navbar has already been done!!

**Comment by AvineshTripathi** [comment] 2022-08-20 12:15
@chirag0002 oh I didn't know that closing this issue you can look for other issues if not let me know I ll help you find one

**Closed by AvineshTripathi** 2022-08-20 12:15 UTC
Labels: bug, triage/awaiting
